"""Text analyzer: extracts key facts and candidate statements from raw encyclopedic text."""
from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class Fact:
    subject: str
    predicate: str
    value: str
    raw: str


def split_sentences(text: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", text)
    return [s.strip() for s in sentences if len(s.strip()) > 20]


def extract_facts(text: str, subject: str = "") -> list[Fact]:
    facts: list[Fact] = []
    for sentence in split_sentences(text):
        if "=" in sentence or "bir" in sentence.lower():
            value = _find_value(sentence)
            if value:
                facts.append(Fact(subject=subject, predicate=sentence[:60], value=value, raw=sentence))
        if re.search(r"\b(19|20)\d{2}\b", sentence):
            year = re.search(r"\b(19|20)\d{2}\b", sentence)
            facts.append(Fact(subject=subject, predicate="yıl", value=year.group(0), raw=sentence))
    return facts


def _find_value(sentence: str) -> str:
    match = re.search(r":\s*([^,;.]+)", sentence)
    if match:
        return match.group(1).strip()
    return ""


def classify_topic(text: str) -> str:
    lowered = text.lower()
    keywords = {
        "Göktürkler": ["türk", "kağanlık", "orhun", "yazıt", "bumin"],
"Uygur Kağanlığı": ["maniheizm", "yerleşik", "matbaa", "kağıt", "töre"],
"Karahanlılar": ["satuk buğra han", "ilk müslüman", "türk-islam", "edebiyat", "karahan"],
"Büyük Selçuklu": ["malazgirt", "nizamülmülk", "tuğrul bey", "alparslan", "vezir"],
"Anadolu Selçuklu": ["konya", "kervansaray", "gevher nesibe", "medrese", "haçlı"],
"Osmanlı İmparatorluğu": ["fatih sultan mehmet", "kanuni", "yavuz", "istanbul", "divan"],
"Kurtuluş Savaşı": ["atatürk", "kurtuluş", "cephe", "kuva-yi milliye", "kongre"],
"Türkiye Cumhuriyeti": ["29 ekim", "ankara", "tbmm", "laiklik", "inkılap"],
"Türkiye coğrafyası": ["anadolu", "üç kıta", "boğazlar", "havza", "tektonik"],
"Türkiye iklimi": ["akdeniz iklimi", "karasal", "karadeniz iklimi", "yağış", "kuraklık"],
"Türkiye dağları": ["ağrı dağ", "erciyes", "kaçkar", "toroslar", "palandöken"],
"Türkiye nehirleri": ["kızılırmak", "fırat", "dicle", "yeşilırmak", "sakarya"],
"Türkiye gölleri": ["van gölü", "tuz gölü", "beyşehir", "eğirdir", "sapanca"],
"Türkiye ovaları": ["çukurova", "konya ovası", "bafra", "çarşamba", "harran"],
"Türkiye bölgeleri": ["marmara", "ege", "akdeniz", "iç anadolu", "karadeniz"],
"türk tarihi": ["tarih", "kronoloji", "savaş", "antlaşma", "fetih"],
"türk mitolojisi": ["ergenekon", "bozkurt", "türeyiş", "gök tanrı", "umay"],
"türk kültürü": ["gelenek", "görenek", "halk", "töre", "bayram"],
"türk mimarisi": ["mimar sinan", "kümbet", "türbe", "cami", "külliye"],
"türk edebiyatı": ["destan", "koşuk", "sagu", "divan", "tanzimat"],
"türk dili": ["göktürkçe", "eski türkçe", "osmanlıca", "türkçe", "lehçe"],
"türk sanatı": ["ebru", "hat", "tezhip", "minyatür", "çini"],
"türk müziği": ["bağlama", "ney", "kemençe", "türkü", "makam"],
"türk folklorü": ["zeybek", "halay", "horon", "kaşık", "bar"],
"türk mutfağı": ["mantı", "lahmacun", "döner", "iskender", "börek"],
"türk folklorik öğeler": ["kilim", "keçe", "dokuma", "nazar boncuğu", "kahve"],
"türk sporları": ["cirit", "yağlı güreş", "okçuluk", "matrak", "gökbörü"],
"türk basını": ["takvim-i vekayi", "tercüman-ı ahval", "gazete", "dergi", "matbaa"],
"türk sineması": ["yeşilçam", "can yoldaş", "yönetmen", "oyuncu", "festival"],
"türk tiyatrosu": ["karagöz", "orta oyunu", "meddah", "tuluat", "sahne"],
"türk eğitimi": ["enderun", "medrese", "mektep", "köy enstitüsü", "üniversite"],
"türk bilimi": ["ali kuşçu", "biruni", "ibn sina", "rasathane", "astronomi"],
"türk tıp tarihi": ["darüşşifa", "bimarhane", "hekim", "cerrahi", "nabız"],
"türk hukuku": ["mecelle", "kanunname", "anayasa", "töre", "kadı"],
"türk ekonomisi": ["ahilik", "lonca", "gedik", "enflasyon", "sanayi"],
"türk tarımı": ["imparatorluk", "çiftçi", "hasat", "imece", "ziraat"],
"türk ticaret": ["ipek yolu", "baharat yolu", "kervan", "tüccar", "panayır"],
"türk denizcilik": ["barbaros", "çaka bey", "levend", "kadırga", "donanma"],
"türk havacılık": ["vecihi hürkuş", "hezarfen", "tayyare", "uçak", "pist"],
"türk demiryolları": ["bağdat demiryolu", "hicaz demiryolu", "gar", "lokomotif", "tren"],
"türk telekomünikasyon": ["telgraf", "telefon", "ptt", "telsiz", "frekans"],
"türk enerji": ["bor", "petrol", "baraj", "hidroelektrik", "kömür"],
"türk savunma": ["yeniçeri", "sipahi", "akıncı", "mehter", "silah"],
"türk siyaset": ["meclis", "parti", "seçim", "muhalefet", "demokrasi"],
"türk yerel yönetim": ["köy", "bucak", "ilçe", "il", "belediye"],
"türk dış politika": ["lozan", "montrö", "nato", "bm", "bağlantısızlar"],
"türk turizm": ["kapadokya", "pamukkale", "efes", "alyuvar", "sahil"],
"türk folklorik kıyafet": ["şalvar", "cepken", "fes", "yaşmak", "bindallı"],
"türk gelenekleri": ["kına gecesi", "sünnet", "asker uğurlama", "bayram", "nişan"],
"osmanlı devleti": ["osmanlı", "padişah", "sultan", "devlet-i aliyye", "vezir"],
"türkiye cumhuriyeti": ["cumhuriyet", "cumhurbaşkanı", "meclis", "başkent", "ilke"],
"türkiye coğrafyası": ["dağ", "nehir", "göl", "ova", "bölge"],
"türk tarihi": ["tarih", "savaş", "antlaşma", "kongre", "mücadele"],
"türk kültürü": ["gelenek", "kültür", "halk", "müzik", "sanat"],
"spor - futbol": ["futbol", "lig", "takım", "gol", "şampiyon"],
"türkiye ekonomi": ["enflasyon", "ihracat", "sanayi", "tarım", "borsa"],
"türkiye turizm": ["otel", "sahil", "müze", "turist", "tatil"],
"türkiye eğitim": ["üniversite", "okul", "sınav", "öğrenci", "yök"],
"türkiye ulaşım": ["otoyol", "havalimanı", "hızlı tren", "köprü", "metro"],
"türkiye mutfağı": ["kebap", "baklava", "çay", "kahve", "lokanta"],
"türkiye enerji": ["doğalgaz", "baraj", "nükleer", "petrol", "yenilenebilir"],
"türkiye iklim": ["akdeniz", "karasal", "karadeniz", "mevsim", "yağış"],
"türkiye teknoloji": ["yazılım", "girişim", "yapay zeka", "bilişim", "ar-ge"],
"türkiye savunma": ["iha", "siha", "savunma sanayii", "askeri", "silah"],
"türkiye sinema": ["yönetmen", "film", "festival", "oyuncu", "senaryo"],
"türkiye müzik": ["halk müziği", "sanat müziği", "pop", "konser", "albüm"],
"türkiye edebiyat": ["roman", "şiir", "yazar", "şair", "hikaye"],
"türkiye mimari": ["selçuklu", "osmanlı", "cami", "saray", "restorasyon"],
"türkiye tarım": ["buğday", "fındık", "çay", "pamuk", "meyvancılık"],
"türkiye sanayi": ["otomotiv", "tekstil", "demir çelik", "petrokimya", "üretim"],
"türkiye finans": ["merkez bankası", "bankacılık", "kredi", "faiz", "yatırım"],
"türkiye basın": ["gazete", "televizyon", "medya", "haber", "dergi"],
"türkiye hukuk": ["anayasa", "mahkeme", "kanun", "adalet", "savcı"],
"türkiye siyaset": ["parti", "seçim", "muhalefet", "iktidar", "bakanlık"],
"türkiye sağlık": ["hastane", "doktor", "şehir hastanesi", "ilaç", "tedavi"],
"türkiye yerel yönetim": ["belediye", "muhtar", "valilik", "kaymakamlık", "ilçe"],
"türkiye basın ve yayın": ["ajans", "yayın", "matbaa", "ansiklopedi", "bülten"],
"türkiye denizcilik": ["liman", "tersane", "gemi", "kabotaj", "boğaz"],
"türkiye havacılık": ["pilot", "uçak", "terminal", "hava yolu", "sefer"],
"türkiye telekomünikasyon": ["fiber", "operatör", "şebeke", "internet", "hat"],
"türkiye madencilik": ["bor", "kömür", "mermer", "bakır", "altın"],
"türkiye folklor": ["zeybek", "halay", "horon", "bar", "türkü"],
"türkiye gelenek": ["nişan", "düğün", "kına", "sünnet", "bayram"],
"türkiye el sanatları": ["halı", "kilim", "çini", "ebru", "bakırcılık"],
"türkiye antropoloji": ["göbeklitepe", "çatalhöyük", "kazı", "höyük", "arkeoloji"],
"türkiye müzecilik": ["topkapı", "ayasofya", "ephesus", "etnoğrafya", "koleksiyon"],
"türkiye yer altı kaynakları": ["linyit", "krom", "mermer", "civa", "boksit"],
"türkiye ormancılık": ["çam", "meşe", "gürgen", "milli park", "ağaçlandırma"],
"türkiye hayvancılık": ["büyükbaş", "küçükbaş", "arıcılık", "ipek böceği", "kümes"],
"türkiye su ürünleri": ["balıkçılık", "alabalık", "levrek", "çipura", "midye"],
"türkiye meteoroloji": ["tahmin", "radar", "sıcaklık", "basınç", "rüzgar"],
"türkiye çevre": ["geri dönüşüm", "erozyon", "atık", "sıfır atık", "kuraklık"],
"türkiye şehircilik": ["imar", "kentleşme", "toplu konut", "park", "altyapı"],
"türkiye demiryolu ağları": ["yht", "marmaray", "banliyö", "hızlı tren", "istasyon"],
"türkiye karayolları": ["otoyol", "tünel", "viyadük", "çevreyolu", "asfalt"],
"türkiye limanları": ["ambarlı", "mersin", "izmir", "alsancak", "haydarpaşa"],
"türkiye havacılık sektörü": ["dhmi", "thy", "pegasus", "bilet", "kabin"],
"türkiye bilişim": ["e-devlet", "siber güvenlik", "yapay zeka", "veri", "kodlama"],
"türkiye uzay": ["tua", "göktürk", "türksat", "uydu", "roket"],
"türkiye nükleer": ["akkuyu", "sinop", "radyasyon", "uranyum", "reaktör"],
"türkiye yenilenebilir enerji": ["güneş", "rüzgar", "jeotermal", "hidroelektrik", "biyokütle"],
"türkiye bankacılık": ["ziraat", "iş bankası", "garanti", "akbank", "vakıfbank"],
"türkiye borsa": ["bist", "hisse", "endeks", "halka arz", "aracı kurum"],
"türkiye sigortacılık": ["kasko", "trafik", "dask", "poliçe", "prim"],
"türkiye gayrimenkul": ["konut", "arsa", "tapu", "kentsel dönüşüm", "kira"],
"türkiye otomotiv": ["togg", "tofaş", "oyak renault", "ford otosan", "hyundai"],
"türkiye tekstil sektörü": ["kumaş", "hazır giyim", "moda", "ihracat", "iplik"],
"türkiye gıda": ["unlu mamul", "süt", "et", "şeker", "yağ"],
"türkiye kimya": ["gübre", "boya", "ilaç", "plastik", "deterjan"],
"türkiye maden sanayi": ["ferrokrom", "alüminyum", "çinko", "kurşun", "antimon"],
"türkiye lojistik": ["nakliye", "kargo", "depolama", "taşımacılık", "gümrük"],
"türkiye perakende": ["market", "avm", "zincir", "e-ticaret", "mağaza"],
"türkiye medya": ["rtük", "basın ilan", "ajans", "gazeteci", "televizyon"],
"türkiye radyo": ["trt", "frekans", "yayın", "fm", "stüdyo"],
"türkiye dijital medya": ["sosyal medya", "youtube", "podcast", "influencer", "blog"],
"türkiye tiyatro sahneleri": ["devlet tiyatroları", "şehir tiyatroları", "sahne", "oyun", "perde"],
"türkiye bale ve opera": ["devlet opera", "bale", "sahne", "eser", "korist"],
"türkiye güzel sanatlar": ["resim", "heykel", "sergi", "galeri", "sanatçı"],
"türkiye kütüphaneler": ["milli kütüphane", "yazma eserler", "arşiv", "kitap", "okuma odası"],
"türkiye dernekler": ["sivil toplum", "vakıf", "dernek", "bağış", "gönüllü"],
"türkiye spor kulüpleri": ["beşiktaş", "fenerbahçe", "galatasaray", "trabzonspor", "başakşehir"],
"türkiye federasyonlar": ["tff", "tbf", "tvf", "thf", "federasyon"],
"türkiye olimpiyat": ["milli takım", "madalya", "sporcu", "kamp", "kota"],
"türkiye geleneksel sporlar": ["cirit", "gıcır", "güreş", "şalvar güreşi", "aba güreşi"],
"türkiye doğa sporları": ["dağcılık", "trekking", "rafting", "kampçılık", "yamaç paraşütü"],
"türkiye kış turizmi": ["uludağ", "palandöken", "erciyes", "kartalkaya", "sarıkamış"],
"türkiye yaz turizmi": ["bodrum", "antalya", "çeşme", "marmaris", "fethiye"],
"türkiye termal turizm": ["afyon", "pamukkale", "yalova", "köz", "kaplıca"],
"türkiye inanç turizmi": ["sümela", "mevlana", "ayasofya", "sumela", "selimiye"],
"türkiye gastronomi turizmi": ["gaziantep", "hatay", "şanlıurfa", "adana", "afyonkarahisar"],
"türkiye sağlık turizmi": ["estetik", "saç ekimi", "diş", "klinik", "hasta"],
"türkiye kongre turizmi": ["fuar", "kongre", "zirve", "toplantı", "salon"],
"türkiye kamp turizmi": ["karavan", "çadır", "doğa", "koy", "mesire"],
"türkiye milli parklar": ["kaz dağları", "yedigöller", "munzur", "köprülü kanyon", "nemrut"],
"türkiye tabiat parkları": ["abant", "saklıkent", "kurşunlu", "ballıkayalar", "ayder"],
"türkiye mağaralar": ["karain", "damlataş", "cennet cehennem", "ilgarini", "gilindire"],
"türkiye şelaleler": ["düden", "kurşunlu", "tortum", "kapuzbaşı", "manavgat"],
"türkiye kanyonlar": ["valla", "cehennem dere", "saklıkent", "ulaş", "köprülü"],
"türkiye platolar": ["haymana", "cihanbeyli", "uzunyayla", "obruk", "bolu"],
"türkiye körfezler": ["edremit", "izmir", "güllük", "gökova", "fethiye"],
"türkiye yarımadalar": ["çanakkale", "biga", "datça", "tekke", "kocaeli"],
"türkiye adalar": ["gökçeada", "bozcaada", "marmara", "avşa", "büyükada"],
"türkiye boğazlar": ["istanbul boğazı", "çanakkale boğazı", "akıntı", "marmara", "karadeniz"],
"türkiye fay hatları": ["kuzey anadolu", "doğu anadolu", "batı anadolu", "deprem", "sismik"],
"türkiye volkanik dağlar": ["ağrı", "nemrut", "süphan", "tendürek", "melendiz"],
"türkiye akarsu rejimleri": ["düzenli", "düzensiz", "akım", "taşkın", "kurak"],
"türkiye toprak tipleri": ["kahverengi", "kestane", "alüvyal", "laterit", "terra rossa"],
"türkiye bitki örtüsü": ["maki", "bozkır", "orman", "garig", "pseudomaki"],
"türkiye endemik türler": ["sığla", "kazdağı göknarı", "isparta gülü", "anadolu lalesi", "ters lale"],
"türkiye hayvan türleri": ["van kedisi", "kangal", "akbaş", "türk tazısı", "alabay"],
"türkiye kuş türleri": ["kelaynak", "telli turna", "flamingo", "anadolu sıvacısı", "keklik"],
"türkiye deniz canlıları": ["hamsi", "palamut", "lüfer", "uskumru", "kalkan"],
"türkiye tarım ürünleri": ["incir", "kayısı", "üzüm", "zeytin", "turunçgil"],
"türkiye endüstri bitkileri": ["tütün", "şeker pancarı", "haşhaş", "keten", "kenevir"],
"türkiye meyvecilik": ["elma", "armut", "şeftali", "kiraz", "vişne"],
"türkiye sebzecilik": ["domates", "biber", "patlıcan", "salatalık", "fasulye"],
"türkiye baklagiller": ["mercimek", "nohut", "fasulye", "bakla", "bezelye"],
"türkiye yağlı tohumlar": ["ayçiçeği", "soya", "yer fıstığı", "kanola", "susam"],
"türkiye hayvancılık türleri": ["kıl keçisi", "tiftik keçisi", "merinos", "manda", "arı"],
"türkiye süt ürünleri": ["peynir", "yoğurt", "ayran", "tereyağı", "lor"],
"türkiye et ürünleri": ["sucuk", "pastırma", "kavurma", "sosis", "salam"],
"türkiye unlu mamuller": ["ekmek", "simit", "pide", "lahmacun", "açma"],
"türkiye tatlılar": ["künefe", "sütlaç", "kazandibi", "kazez", "revani"],
"türkiye içecekler": ["şalgam", "boza", "ayran", "salep", "şerbet"],
"türkiye baharatlar": ["pul biber", "kekik", "nane", "kimyon", "sumak"],
"türkiye zeytinyağlılar": ["yaprak sarması", "imam bayıldı", "pazı", "mücver", "kısır"],
"türkiye çorbalar": ["mercimek", "ezogelin", "tarhana", "işkembe", "yayla"],
"türkiye yöresel yemekler": ["mantı", "etliekmek", "ciğer", "iskender", "hünkarbeğendi"],
"türkiye kahvaltılık": ["zeytin", "peynir", "bal", "kaymak", "menemen"],
"türkiye sokak lezzetleri": ["kokoreç", "midye dolma", "balık ekmek", "kumpir", "nohut pilav"],
"türkiye geleneksel tatlar": ["lokum", "cezerye", "pişmaniye", "helva", "macun"],
"türkiye halk oyunları": ["bar", "horon", "halay", "zeybek", "karşılama"],
"türkiye çalgıları": ["bağlama", "kabak kemane", "zurna", "davul", "kaval"],
"türkiye türküleri": ["uzun hava", "bozlak", "kırık hava", "hoyrat", "barak"],
"türkiye geleneksel el sanatları": ["dokumacılık", "ebru", "tezhip", "hat", "minyatür"],
"türkiye mimari unsurlar": ["şadırvan", "mihrap", "minber", "kubbe", "avlu"],
"türkiye tarihi yapılar": ["kızkulesi", "galata kulesi", "topkapı sarayı", "dolmabahçe", "sümela"],
"türkiye antik kentler": ["troya", "efes", "milet", "perge", "aspendos"],
"türkiye kaleler": ["rumeli hisarı", "anadolu hisarı", "alanya kalesi", "bodrum kalesi", "van kalesi"],
"türkiye köprüler": ["15 temmuz şehitler köprüsü", "fatih sultan mehmet", "yavuz sultan selim", "osmangazi", "19 çanakkale"],
"türkiye tüneller": ["bolu tüneli", "marmaray", "avrasya", "devrent", "zigana"],
"türkiye meydanlar": ["taksim", "kızılay", "sultanahmet", "konak", "cumhuriyet"],
"türkiye caddeler": ["istiklal", "bağdat", "tunalı hilmi", "kordon", "porsuk"],
"türkiye parklar": ["emirgan", "yıldız", "gezi", "atatürk", "kuğulu"],
"türkiye göletler": ["mogan", "eymir", "seyfe", "akşehir", "burdur"],
"türkiye akarsu havzaları": ["karadeniz", "akdeniz", "marmara", "basra", "iç anadolu"],
"türkiye iklim tipleri": ["akdeniz", "karasal", "karadeniz", "marmara", "sert karasal"],
"türkiye toprak çeşitleri": ["zonal", "intrazonal", "azonal", "podsol", "çernezyom"],
"türkiye bitki örtüsü tipleri": ["makilik", "bozkır", "orman", "yapraklı", "iğne yapraklı"],
"türkiye ağaç türleri": ["kayın", "gürgen", "meşe", "çam", "köknar"],
"türkiye çiçek türleri": ["lale", "sümbül", "nergis", "karanfil", "papatya"],
"türkiye meyve ağaçları": ["incir", "zeytin", "nar", "dut", "ayva"],
"türkiye tahıl ürünleri": ["buğday", "arpa", "çavdar", "yulaf", "mısır"],
"türkiye bakliyat çeşitleri": ["mercimek", "nohut", "fasulye", "bakla", "maş"],
"türkiye endüstriyel tarım": ["pamuk", "tütün", "şekerpancar", "haşhaş", "keten"],
"türkiye sebze çeşitleri": ["domates", "biber", "patlıcan", "salatalık", "kabak"],
"türkiye meyve çeşitleri": ["elma", "armut", "şeftali", "kayısı", "üzüm"],
"türkiye narenciye": ["portakal", "mandalina", "limon", "greyfurt", "turunç"],
"türkiye kuruyemiş": ["fındık", "fıstık", "ceviz", "badem", "leblebi"],
"türkiye baharat çeşitleri": ["kimyon", "karabiber", "kekik", "nane", "tarçın"],
"türkiye hayvancılık kolları": ["büyükbaş", "küçükbaş", "kümes", "arıcılık", "ipek böcekçiliği"],
"türkiye et çeşitleri": ["kırmızı et", "beyaz et", "sakatat", "kıyma", "kuşbaşı"],
"türkiye süt çeşitleri": ["inek", "koyun", "keçi", "manda", "keçi sütü"],
"türkiye peynir çeşitleri": ["beyaz peynir", "kaşar", "tulum", "lor", "otlu peynir"],
"türkiye yoğurt çeşitleri": ["süzme yoğurt", "yayla yoğurt", "kaymaklı yoğurt", "kese yoğurt", "meyveli yoğurt"],
"türkiye yağ çeşitleri": ["zeytinyağı", "ayçiçek", "mısırözü", "tereyağı", "kuyruk yağı"],
"türkiye ekmek çeşitleri": ["somun", "pide", "bazlama", "yufka", "lavash"],
"türkiye çorba çeşitleri": ["mercimek", "tarhana", "yayla", "ezogelin", "kelle paça"],
"türkiye ana yemekler": ["karnıyarık", "hünkarbeğendi", "tas kebabı", "kuru fasulye", "et sote"],
"türkiye pilav çeşitleri": ["pirinç pilavı", "bulgur", "şehriyeli", "iç pilav", "firik"],
"türkiye dolma çeşitleri": ["yaprak sarması", "biber dolması", "kabak dolması", "lahana", "mumbar"],
"türkiye börek çeşitleri": ["su böreği", "kol böreği", "sigara böreği", "gözleme", "pişi"],
"türkiye tatlı çeşitleri": ["baklava", "kadayıf", "künefe", "revani", "şekerpare"],
"türkiye hamur işleri": ["manti", "erişte", "mantı", "gözleme", "bazlama"],
"türkiye içecek çeşitleri": ["çay", "kahve", "ayran", "şalgam", "boza"],
"türkiye alkollü içecekler": ["rakı", "bira", "şarap", "kanyak", "cin"],
"türkiye meyve suları": ["vişne", "şeftali", "kayısı", "portakal", "elma suyu"],
"türkiye sokak yemekleri": ["simit", "açma", "poğaça", "boyoz", "gevrek"],
"türkiye tatlı atıştırmalıklar": ["lokum", "pişmaniye", "helva", "macun", "cezerye"],
"türkiye yöresel çorbalar": ["beyran", "yufalama", "arabaşı", "tohma", "kesme"],
"türkiye yöresel tatlar": ["künefe", "katmer", "baklava", "künefe", "pestil"],
"türkiye zeytinyağlılar": ["börülce", "enginar", "imambayıldı", "şakşuka", "barbunya"],
"türkiye etli yemekler": ["testi kebabı", "tandıro", "büryan", "kuyu", "ciğer"],
"türkiye balık yemekleri": ["hamsi tava", "buğulama", "ızgara", "kalkan", "levrek"],
"türkiye salatalar": ["çoban", "gavurdağı", "meze", "patates", "piyaz"],
"türkiye mezeler": ["haydari", "şakşuka", "humus", "babagannuş", "muhammara"],
"türkiye soslar": ["acuka", "salça", "cacık", "tarator", "mıhlama"],
"türkiye kahvaltılıklar": ["menemen", "mıhlama", "sucuklu yumurta", "bazlama", "tahin pekmez"],
"türkiye reçeller": ["gül", "vişne", "incir", "çilek", "turunç"],
"türkiye kurular": ["kayısı", "üzüm", "incir", "erik", "dut"],
"türkiye baharatlılar": ["pul biber", "isot", "nane", "kekik", "köri"],
"türkiye bitki çayları": ["adaçayı", "ihlamur", "papatya", "rezene", "kuşburnu"],
"türkiye kahve çeşitleri": ["türk kahvesi", "menengiç", "dibek", "süvari", "mürver"],
"türkiye geleneksel oyunlar": ["saklambaç", "körebe", "uzun eşek", "çelik çomak", "misket"],
"türkiye çocuk şarkıları": ["dandi", "mini mini", "bebek", "okul", "tatil"],
"türkiye ninni çeşitleri": ["fış fış kayıkçı", "dandini", "uyusun da büyüsün", "bebek ninnisi", "kış ninnisi"],
"türkiye masallar": ["keloğlan", "nasreddin hoca", "Keloğlan", "keloğlan masalları", "nasreddin"],
"türkiye efsaneler": ["şahmeran", "ferhat ile şirin", "leyla ile mecnun", "aslı ile kerem", "köroğlu"],
"türkiye halk kahramanları": ["köroğlu", "dadaloğlu", "pir sultan", "karacaoğlan", "yunus emre"],
"türkiye ozanlar": ["veysel", "mahzuni", "neşet ertaş", "veysel şatıroğlu", "pir sultan"],
"türkiye şairler": ["nazım hikmet", "orhan veli", "necip fazıl", "atilla ilhan", "cemal süreya"],
"türkiye yazarlar": ["yaşar kemal", "orhan pamuk", "ahmet hamdi", "halide edip", "reşat nuri"],
"türkiye filozoflar": ["farabi", "ibn sina", "gazali", "mevlana", "hacı bektaş"],
"türkiye bilim insanları": ["oktay sinanoğlu", "aziz sancar", "feza gürsey", "cahit arf", "hulusi behçet"],
"türkiye mucitler": ["vecihi hürkuş", "nuri demirağ", "ismail hakki", "tevfik", "mühendis"],
"türkiye sporcular": ["naim süleymanoğlu", "halil mutlu", "nida", "yasemin adar", "mete gazoz"],
"türkiye teknik direktörler": ["fatih terim", "şenol güneş", "mustafa denizli", "abdullah avcı", "sergen yalçın"],
"türkiye futbolcular": ["hakan şükür", "lefter", "metin oktay", "burak yılmaz", "arda turan"],
"türkiye basketbolcular": ["hidayet türkoğlu", "mehmet okur", "ersan ilyasova", "cedi osman", "alperen şengün"],
"türkiye voleybolcular": ["neslihan demir", "eda erdem", "zehra güneş", "ebrar karakurt", "melissa vargas"],
"türkiye güreşçiler": ["yaşar doğu", "hamza yerlikaya", "taha akgül", "rıza kayaalp", "kazım karabekir"],
"türkiye haldeciler": ["halil mutlu", "naim", "sunay", "nurcan taylan", "reşat"],
"türkiye atletsizler": ["süreyya ayhan", "elvan abeylegesse", "rıza", "ilham", "ramazan"],
"türkiye yüzücüler": ["emre sakçı", "viktoriya güneş", "kuzey tunçelli", "deniz", "bora"],
"türkiye boksörler": ["sinan şamil sam", "busenaz sürmeneli", "buse naz çakıroğlu", "adem kılıçcı", "atanur"],
"türkiye yelkenciler": ["ali", "bora", "deniz", "yelken", "regatta"],
"türkiye yelkencilik": ["tekne", "rüzgar", "kürek", "müsabaka", "yarış"],
"türkiye dağcılık kulüpleri": ["tkdf", "tulos", "zirve", "dağcı", "tırmanış"],
"türkiye izcilik": ["tuy", "kamp", "izci", "fular", "doğa"],
"türkiye havacılık kulüpleri": ["thk", "model uçak", "planör", "paraşüt", "balon"],
"türkiye otomobil sporları": ["tso", "ralli", "pist", "drift", "karting"],
"türkiye motor sporları": ["kenan sofuoğlu", "toprak razgatlıoğlu", "motokros", "pist", "motor"],
"türkiye at yarışları": ["veliefendi", "jokey", "safkan", "hipodrom", "galop"],
"türkiye geleneksel oyunlar": ["çelik", "çomak", "uzun", "eşek", "körebe"],
"türkiye zeka oyunları": ["mangal", "dokuz taş", "go", "satranç", "sudoku"],
"türkiye halk oyunları ekipleri": ["bar", "halay", "zeybek", "horon", "karşılama"],
"türkiye yerel festivaller": ["deve güreşi", "yağlı güreş", "mesir macunu", "kırkpınar", "kadırga"],
"türkiye uluslararası festivaller": ["antalya altın portakal", "istanbul film festivali", "iksv", "devlet", "konser"],
"türkiye fuarlar": ["tüyap", "izfuar", "kitap fuarı", "tarım fuarı", "savunma sanayi"],
"türkiye müzeler": ["topkapı", "ayasofya", "etnografya", "arkeoloji müzesi", "rahmi koç"],
"türkiye saraylar": ["topkapı", "dolmabahçe", "yıldız", "beylerbeyi", "çırağan"],
"türkiye kasırlar": ["küçüksu", "ihlamur", "maslak", "aynalıkavak", "florya"],
"türkiye yalılar": ["bosfor", "kandilli", "vaniköy", "kanlıca", "anadoluhisarı"],
"türkiye hanlar": ["koza han", "büyük han", "valide han", "emir han", "zincirli han"],
"türkiye hamamlar": ["çemberlitaş", "haseki hürrem", "cağaloğlu", "galatasaray", "gedikpaşa"],
"türkiye çeşmeler": ["ahmet iii", "tophane", "uskudar", "mahmut", "meydan"],
"türkiye sebil": ["sebil", "su", "çeşme", "hayrat", "kitabe"],
"türkiye türbeler": ["eyüp sultan", "mevlana", "hacı bayram", "aziz mahmud", "telli baba"],
"türkiye camiler": ["sultanahmet", "süleymaniye", "selimiye", "ayasofya", "ortaköy"],
"türkiye kiliseler": ["saint antoine", "ayorgi", "akdamar", "meryem ana", "sumela"],
"türkiye sinagoglar": ["neve şalom", "ahrida", "etz hayim", "hekim", "galata"],
"türkiye manastırlar": ["sumela", "alakeçili", "akyazı", "gümüşhane", "mardin"],
"türkiye ören yerleri": ["göbeklitepe", "nemrut", "hattuşa", "efes", "hierapolis"],
"türkiye antik tiyatrolar": ["aspendos", "side", "patara", "myra", "hierapolis"],
"türkiye su kemerleri": ["valens", "mağlova", "uzunkemer", "kırkçeşme", "su kemeri"],
"türkiye sarnıçlar": ["yerebatan", "binbirdirek", "theodosius", "sarnıç", "su"],
"türkiye kuleler": ["galata", "kızkulesi", "beyazıt", "atakule", "saat kulesi"],
"türkiye saat kuleleri": ["izmir", "bursa", "adana", "çanakkale", "izmit"],
"türkiye heykeller": ["atatürk", "zafer", "cumhuriyet", "mimar sinan", "yunus emre"],
"türkiye anıtlar": ["anıtkabir", "çanakkale şehitliği", "zafer anıtı", "özgürlük", "hürriyet"],
"türkiye mezarlıklar": ["zincirlikuyu", "eyüp", "karacaahmet", "aşiyan", "cebeci"],
"türkiye köprüler tarihi": ["mağlova", "merit", "büyükçekmece", "kemer", "taşköprü"],
"türkiye kaleler tarihi": ["rumeli", "anadolu", "kilitbahir", "namazgah", "yedikule"],
"türkiye surlar": ["istanbul surları", "diyarbakır surları", "antalya surları", "iznik surları", "trabzon"],
"türkiye kapılar tarihi": ["bab-ı humayun", "harput", "mardin", "kars", "edirne"],
"türkiye evleri tarihi": ["safranbolu", "beypazarı", "mardin evleri", "amasya evleri", "cumalıkızık"],
"türkiye sokakları tarihi": ["tarihi yarımada", "kaleiçi", "asmalı mescit", "karaköy", "balat"],
"türkiye çarşıları": ["kapalıçarşı", "mısır çarşısı", "kemeraltı", "uzun çarşı", "bakırcılar"],
"türkiye pasajlar": ["çiçek pasajı", "suriyiye", "kapan", "halep", "atlas"],
"türkiye sinemalar tarihi": ["emk", "riza paşa", "ipek", "melek", "atlas sineması"],
"türkiye tiyatrolar tarihi": ["darülbedayi", "tepebaşı", "gedikpaşa", "muhsin ertuğrul", "sahne"],
"türkiye gazeteler tarihi": ["takvim-i vekayi", "hâkimiyet-i milliye", "ikdam", "tanin", "cumhuriyet"],
"türkiye dergiler tarihi": ["servet-i fünun", "genç kalemler", "varlık", "türk dili", "akbaba"],
"türkiye matbaalar tarihi": ["ibrahim müteferrika", "matbaa", "baskı", "harf", "mürekkep"],
"türkiye kütüphaneler tarihi": ["şehit ali paşa", "köprülü", "fatih", "süleymaniye", "beyazıt"],
"türkiye okullar tarihi": ["mekteb-i sultani", "mülkiye", "harbiye", "tibbiye", "darüşşafaka"],
"türkiye hastaneler tarihi": ["gureba", "zeynep kamil", "haydarpaşa numune", "şişli etfal", "cerrahpaşa"],
"türkiye fabrikalar tarihi": ["hereke", "bakırköy", "tüpraş", "ereğli", "kardemir"],
"türkiye demiryolları tarihi": ["haydarpaşa garı", "sirkeçi garı", "ankara garı", "alsancak", "basmane"],
"türkiye limanlar tarihi": ["salıpazarı", "haydarpaşa", "galata", "izmir", "mersin"],
"türkiye denizcilik tarihi": ["kabotaj", "seyr-i sefain", "deniz yolları", "vapur", "şirket-i hayriye"],
"türkiye havacılık tarihi": ["yeşilköy", "hangar", "tayyarecemiyeti", "ilk uçuş", "pilot"],
"türkiye askeri tarih": ["göktürk", "selçuklu", "osmanlı", "kurtuluş savaşı", "kıbrıs"],
"türkiye dış politika tarihi": ["montrö", "lozan", "sadabat", "balkan antantı", "nato"],
"türkiye anayasalar tarihi": ["kanun-i esasi", "1921", "1924", "1961", "1982"],
"türkiye hükümetler tarihi": ["meclis hükümeti", "icra vekilleri", "kabine", "koalisyon", "tek parti"],
"türkiye seçimler tarihi": ["1946", "1950", "1960", "1980", "2002"],
"türkiye partiler tarihi": ["chp", "dp", "ap", "anap", "ak parti"],
"türkiye nüfus tarihi": ["sayım", "göç", "mübadele", "şehirleşme", "köye dönüş"],
"türkiye ekonomik krizler": ["1929", "1958", "1970", "1994", "2001"],
"türkiye kalkınma planları": ["birinci", "ikinci", "üçüncü", "kalkınma", "plan"],
"türkiye reformlar": ["tanzimat", "islahat", "meşrutiyet", "cumhuriyet", "devrim"],
"türkiye madenler tarihi": ["divriği", "zonguldak", "murgul", "keban", "bor"],
"türkiye barajlar tarihi": ["atatürk", "keban", "karakaya", "altınkaya", "hirfanlı"],
"türkiye karayolları tarihi": ["karayolları genel müdürlüğü", "asfalt", "köprü", "otoyol", "tünel"],
"türkiye telekom tarihi": ["ptt", "türk telekom", "telgrafhane", "telefon santrali", "fiber"],
"türkiye radyo tarihi": ["istanbul radyosu", "ankara radyosu", "izmir radyosu", "telsiz", "yayın"],
"türkiye televizyon tarihi": ["trt 1", "siyah beyaz", "renkli", "özel kanal", "dijital"],
"türkiye internet tarihi": ["metu", "tübitak", "ağ", "bağlantı", "genis bant"],
"türkiye uzay tarihi": ["türksat 1b", "rasat", "göktürk 2", "tübitak uzay", "uydular"],
"türkiye otomotiv tarihi": ["anadol", "murat 123", "şahin", "doğan", "togg"],
"türkiye tekstil tarihi": ["dokuma", "tezgah", "çıkrık", "fabrika", "hazır giyim"],
"türkiye gıda tarihi": ["un", "şeker", "yağ fabrikası", "konserve", "şeker pancarı"],
"türkiye demir çelik tarihi": ["karabük", "ereğli", "iskenderun", "sivas", "divriği"],
"türkiye petrol tarihi": ["raman", "batman", "mardin", "tüpraş", "petrol ofisi"],
"türkiye çimento tarihi": ["darica", "zonguldak", "ankara", "izmir", "fabrika"],
"türkiye cam tarihi": ["paşabahçe", "beykoz", "şişe cam", "kristal", "cam sanayi"],
"türkiye tütün tarihi": ["tekel", "sigara fabrikası", "yaprak tütün", "marmara", "ege"],
"türkiye çay tarihi": ["rize", "çaykur", "harman", "demlik", "fincan"],
"türkiye fındık tarihi": ["giresun", "ordu", "trabzon", "kabuk", "iç fındık"],
"türkiye pamuk tarihi": ["çukurova", "söke", "urfa", "çırçır", "balya"],
"türkiye narenciye tarihi": ["mersin", "antalya", "adana", "hasat", "ihracat"],
"türkiye zeytin tarihi": ["ayvalık", "gemlik", "milas", "zeytinyağı", "sabun"],
"türkiye bağcılık tarihi": ["manisa", "nevşehir", "elazığ", "tekirdağ", "şarapçılık"],
"türkiye hayvancılık tarihi": ["mera", "yaylak", "kışlak", "otlak", "büyükbaş"],
"türkiye arıcılık tarihi": ["marmaris", "anzer", "siirt", "hakkari", "petek"],
"türkiye ipek böcekçiliği tarihi": ["bursa", "diyarbakır", "koza", "iplik", "tut yaprağı"],
"türkiye balıkçılık tarihi": ["dalyan", "çapar", "ağ", "gırgır", "trol"],
"türkiye ormancılık tarihi": ["orman idaresi", "ağaçlandırma", "yangın", "kereste", "tomruk"],
"türkiye madencilik tarihi": ["zonguldak kömür", "divriği demir", "murgul bakır", "gulam", "mühendis"],
"türkiye enerji tarihi": ["hidroelektrik", "termik", "nükleer", "rüzgar", "güneş"],
"türkiye ulaşım tarihi": ["vapur", "tren", "fayton", "otobüs", "uçak"],
"türkiye posta tarihi": ["teşkilat-ı mahsusa", "posta", "pul", "mektup", "zarf"],
"türkiye para tarihi": ["akçe", "kuruş", "lira", "kaime", "banknot"],
"türkiye ölçü tarihi": ["okka", "dirhem", "arsın", "metrik", "kantar"],
"türkiye takvim tarihi": ["hicri", "rumi", "miladi", "celali", "takvim"],
"türkiye saat tarihi": ["alaturka", "alafranga", "güneş saati", "kum saati", "duvar saati"],
"türkiye bayrak tarihi": ["al sancak", "hilal", "yıldız", "kırmızı", "kumaş"],
"türkiye armalar tarihi": ["tuğra", "devlet arması", "mühür", "nişan", "ferman"],
"türkiye madalyalar tarihi": ["istiklal madalyası", "imtiyaz", "liyakat", "iftihar", "madalya"],
"türkiye nişanlar tarihi": ["nişan-ı ali osman", "nişan-ı medidi", "mecidiye", "osmani", "nişan"],
"türkiye unvanlar tarihi": ["paşa", "bey", "efendi", "ağa", "hatun"],
"türkiye kıyafetler tarihi": ["kaftan", "şalvar", "ferace", "çarşaf", "frak"],
"türkiye düğünler tarihi": ["görücü", "istemek", "nişan", "kına", "düğün alayı"],
"türkiye cenaze törenleri": ["helallik", "sala", "musalla", "cenaze", "mezar"],
"türkiye inançlar tarihi": ["gök tanrı", "islam", "hristiyanlık", "musevilik", "şamanizm"],
"türkiye gelenekler tarihi": ["hıdrellez", "nevruz", "kandil", "bayram", "aşure"],
"türkiye batıl itikatlar": ["nazar", "kurşun dökme", "muska", "fal", "uğur"],
"türkiye halk hekimliği": ["otacı", "ocak", "sülük", "hacamat", "kocakarı"],
"türkiye mimari tarzlar": ["selçuklu", "beylikler", "osmanlı", "erken cumhuriyet", "milli mimari"],
"türkiye dekorasyon tarihi": ["sedef", "kakma", "edirnekari", "ahşap", "çini"],
"türkiye halı stilleri": ["hereke", "uıak", "milas", "kula", "lâdik"],
"türkiye kilim motifleri": ["elibelinde", "koçboynuzu", "pıtrak", "akrep", "sandık"],
"türkiye çömlekçilik": ["avanos", "iznik", "kütahya", "küp", "testi"],
"türkiye cam sanatları tarihi": ["çeşm-i bülbül", "beykoz işi", "kristal", "üfleme", "boncuk"],
"türkiye dokuma tezgahları": ["üç ayak", "dere", "çözgü", "atkı", "maki"],
    }
    for category, words in keywords.items():
        if any(w in lowered for w in words):
            return category
    return "Türk tarihi"
